/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorTestRouteImport } from './routes/error-test'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as ProductsSearchRouteImport } from './routes/products/search'
import { Route as ProductsAllRouteImport } from './routes/products/all'
import { Route as ProductsCategoryRouteImport } from './routes/products/$category'
import { Route as ProductProductSkuRouteImport } from './routes/product/$productSku'
import { Route as CheckoutOrderConfirmationRouteImport } from './routes/checkout/order-confirmation'
import { Route as AuthMyAccountRouteImport } from './routes/auth/my-account'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const ErrorTestRoute = ErrorTestRouteImport.update({
  id: '/error-test',
  path: '/error-test',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSkuRoute = ProductProductSkuRouteImport.update({
  id: '/product/$productSku',
  path: '/product/$productSku',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderConfirmationRoute =
  CheckoutOrderConfirmationRouteImport.update({
    id: '/checkout/order-confirmation',
    path: '/checkout/order-confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthMyAccountRoute = AuthMyAccountRouteImport.update({
  id: '/auth/my-account',
  path: '/auth/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/error-test': typeof ErrorTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/my-account': typeof AuthMyAccountRoute
  '/checkout/order-confirmation': typeof CheckoutOrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/error-test': typeof ErrorTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/my-account': typeof AuthMyAccountRoute
  '/checkout/order-confirmation': typeof CheckoutOrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
  '/checkout': typeof CheckoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/basket': typeof BasketRoute
  '/error-test': typeof ErrorTestRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/my-account': typeof AuthMyAccountRoute
  '/checkout/order-confirmation': typeof CheckoutOrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
  '/checkout/': typeof CheckoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/basket'
    | '/error-test'
    | '/auth/login'
    | '/auth/my-account'
    | '/checkout/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
    | '/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/basket'
    | '/error-test'
    | '/auth/login'
    | '/auth/my-account'
    | '/checkout/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/basket'
    | '/error-test'
    | '/auth/login'
    | '/auth/my-account'
    | '/checkout/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasketRoute: typeof BasketRoute
  ErrorTestRoute: typeof ErrorTestRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMyAccountRoute: typeof AuthMyAccountRoute
  CheckoutOrderConfirmationRoute: typeof CheckoutOrderConfirmationRoute
  ProductProductSkuRoute: typeof ProductProductSkuRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ProductsAllRoute: typeof ProductsAllRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/error-test': {
      id: '/error-test'
      path: '/error-test'
      fullPath: '/error-test'
      preLoaderRoute: typeof ErrorTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/all': {
      id: '/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSku': {
      id: '/product/$productSku'
      path: '/product/$productSku'
      fullPath: '/product/$productSku'
      preLoaderRoute: typeof ProductProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/order-confirmation': {
      id: '/checkout/order-confirmation'
      path: '/checkout/order-confirmation'
      fullPath: '/checkout/order-confirmation'
      preLoaderRoute: typeof CheckoutOrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/my-account': {
      id: '/auth/my-account'
      path: '/auth/my-account'
      fullPath: '/auth/my-account'
      preLoaderRoute: typeof AuthMyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasketRoute: BasketRoute,
  ErrorTestRoute: ErrorTestRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMyAccountRoute: AuthMyAccountRoute,
  CheckoutOrderConfirmationRoute: CheckoutOrderConfirmationRoute,
  ProductProductSkuRoute: ProductProductSkuRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  ProductsAllRoute: ProductsAllRoute,
  ProductsSearchRoute: ProductsSearchRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
