/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSearchRouteImport } from './routes/products/search'
import { Route as ProductsAllRouteImport } from './routes/products/all'
import { Route as ProductsCategoryRouteImport } from './routes/products/$category'
import { Route as ProductProductSkuRouteImport } from './routes/product/$productSku'

const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSkuRoute = ProductProductSkuRouteImport.update({
  id: '/product/$productSku',
  path: '/product/$productSku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/my-account': typeof MyAccountRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/my-account': typeof MyAccountRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/basket': typeof BasketRoute
  '/checkout': typeof CheckoutRoute
  '/create-account': typeof CreateAccountRoute
  '/login': typeof LoginRoute
  '/my-account': typeof MyAccountRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/basket'
    | '/checkout'
    | '/create-account'
    | '/login'
    | '/my-account'
    | '/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/basket'
    | '/checkout'
    | '/create-account'
    | '/login'
    | '/my-account'
    | '/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/basket'
    | '/checkout'
    | '/create-account'
    | '/login'
    | '/my-account'
    | '/order-confirmation'
    | '/product/$productSku'
    | '/products/$category'
    | '/products/all'
    | '/products/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BasketRoute: typeof BasketRoute
  CheckoutRoute: typeof CheckoutRoute
  CreateAccountRoute: typeof CreateAccountRoute
  LoginRoute: typeof LoginRoute
  MyAccountRoute: typeof MyAccountRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ProductProductSkuRoute: typeof ProductProductSkuRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ProductsAllRoute: typeof ProductsAllRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/all': {
      id: '/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSku': {
      id: '/product/$productSku'
      path: '/product/$productSku'
      fullPath: '/product/$productSku'
      preLoaderRoute: typeof ProductProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BasketRoute: BasketRoute,
  CheckoutRoute: CheckoutRoute,
  CreateAccountRoute: CreateAccountRoute,
  LoginRoute: LoginRoute,
  MyAccountRoute: MyAccountRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ProductProductSkuRoute: ProductProductSkuRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  ProductsAllRoute: ProductsAllRoute,
  ProductsSearchRoute: ProductsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
