/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSearchRouteImport } from './routes/products/search'
import { Route as ProductsAllRouteImport } from './routes/products/all'
import { Route as ProductProductSkuRouteImport } from './routes/product/$productSku'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSearchRoute = ProductsSearchRouteImport.update({
  id: '/products/search',
  path: '/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/products/all',
  path: '/products/all',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductSkuRoute = ProductProductSkuRouteImport.update({
  id: '/product/$productSku',
  path: '/product/$productSku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/product/$productSku': typeof ProductProductSkuRoute
  '/products/all': typeof ProductsAllRoute
  '/products/search': typeof ProductsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/product/$productSku'
    | '/products/all'
    | '/products/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/product/$productSku'
    | '/products/all'
    | '/products/search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/product/$productSku'
    | '/products/all'
    | '/products/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductProductSkuRoute: typeof ProductProductSkuRoute
  ProductsAllRoute: typeof ProductsAllRoute
  ProductsSearchRoute: typeof ProductsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/search': {
      id: '/products/search'
      path: '/products/search'
      fullPath: '/products/search'
      preLoaderRoute: typeof ProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/all': {
      id: '/products/all'
      path: '/products/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSku': {
      id: '/product/$productSku'
      path: '/product/$productSku'
      fullPath: '/product/$productSku'
      preLoaderRoute: typeof ProductProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductProductSkuRoute: ProductProductSkuRoute,
  ProductsAllRoute: ProductsAllRoute,
  ProductsSearchRoute: ProductsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
